import Head from "next/head";
import NavBar from "./NavBar";
import Footer from "./Footer";




export default function DefaultLayout({ children }: { children?: JSX.Element }) {

    return (
        <div>
            <div className="bg-white md:space-y-5  min-h-screen">
                <NavBar />
                <div className="bg max-w-full mx-auto py-5 px-10 md:py-14 md:px-20 min-h-screen md:min-h-0">
                    <main>
                        <Head>
                            <title>InspireSpace</title>
                            <meta name="description" content="Generated by create next app" />
                            <link rel="icon" href="/logo.ico" />
                        </Head>

                        {children}
                    </main>

                </div>

            </div>
            <Footer />
        </div>
    );


}
